//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::account::Entity as Account;
pub use super::permission::Entity as Permission;
pub use super::project::Entity as Project;
pub use super::session::Entity as Session;
pub use super::todo::Entity as Todo;
