//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "todo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub project_id: Option<i32>,
    pub name: String,
    pub user_id: Option<i32>,
    pub permission: Option<i32>,
    pub priority: i32,
    pub content: String,
    pub description: String,
    pub startline: Option<String>,
    pub endline: Option<String>,
    pub parent: Option<i32>,
    pub is_checked: bool,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
